# Generated by Django 2.0.3 on 2018-03-24 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('grahpictype', models.CharField(choices=[('1', '建筑'), ('2', '道路'), ('3', '河流')], max_length=4)),
                ('context', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maptype', models.CharField(choices=[('1', '多光谱'), ('2', '全色彩'), ('3', '混合')], max_length=8)),
                ('name', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('width', models.BigIntegerField()),
                ('height', models.BigIntegerField()),
                ('filepath', models.FileField(upload_to='')),
                ('cut_row', models.IntegerField()),
                ('cut_col', models.IntegerField()),
                ('gen_date', models.DateTimeField()),
                ('folder', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='SliceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_raw', models.IntegerField()),
                ('index_col', models.IntegerField()),
                ('filepath', models.FileField(upload_to='')),
                ('parent_map', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Map')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
