# Generated by Django 2.0.3 on 2018-04-26 07:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSIuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
        ),
        migrations.CreateModel(
            name='GraphicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('grahpictype', models.CharField(choices=[('1', '建筑'), ('2', '道路'), ('3', '河流')], max_length=4)),
                ('grahpiclabel', models.CharField(choices=[('1', '拆迁'), ('2', '违建')], max_length=4)),
                ('context', models.TextField()),
                ('discrib', models.TextField()),
                ('square', models.FloatField(default=0)),
                ('coordinate_x', models.FloatField(default=0)),
                ('coordinate_y', models.FloatField(default=0)),
                ('graphic_provide', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatelliteID', models.CharField(choices=[('1', '高分二号'), ('2', '高景一号'), ('3', '资源一号')], default=False, max_length=20)),
                ('Maptype', models.CharField(blank=True, choices=[('1', '多光谱'), ('2', '全色彩'), ('3', '融合')], default=False, max_length=8)),
                ('SensorID', models.CharField(blank=True, default=False, max_length=20)),
                ('ReceiveTime', models.DateField(blank=True, default=False)),
                ('name', models.TextField(blank=True, default=False, max_length=500)),
                ('Bands', models.IntegerField(blank=True, default=False)),
                ('WidthInPixels', models.IntegerField(blank=True, default=False)),
                ('HeightInPixels', models.IntegerField(blank=True, default=False)),
                ('EarthEllipsoid', models.CharField(blank=True, default=False, max_length=10)),
                ('TopLeftLatitude', models.FloatField(blank=True, default=False)),
                ('TopLeftLongitude', models.FloatField(blank=True, default=False)),
                ('TopRightLatitude', models.FloatField(blank=True, default=False)),
                ('TopRightLongitude', models.FloatField(blank=True, default=False)),
                ('BottomRightLatitude', models.FloatField(blank=True, default=False)),
                ('BottomRightLongitude', models.FloatField(blank=True, default=False)),
                ('BottomLeftLatitude', models.FloatField(blank=True, default=False)),
                ('BottomLeftLongitude', models.FloatField(blank=True, default=False)),
                ('filepath', models.TextField(blank=True, default=False, max_length=500)),
                ('cut_row', models.IntegerField(blank=True, default=False)),
                ('cut_col', models.IntegerField(blank=True, default=False)),
                ('gen_date', models.DateField(blank=True, default=False)),
                ('folder', models.TextField(blank=True, default=False, max_length=500)),
                ('isPublish', models.BooleanField(default=False)),
                ('ProductLevel', models.CharField(blank=True, default=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SliceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_raw', models.IntegerField()),
                ('index_col', models.IntegerField()),
                ('filepath', models.FileField(upload_to='')),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Map')),
            ],
        ),
    ]
