# Generated by Django 2.0.3 on 2018-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='GlobeID',
            field=models.IntegerField(default=False, max_length=8),
        ),
        migrations.AddField(
            model_name='map',
            name='ImageDesc',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='map',
            name='IsUnit8',
            field=models.BooleanField(default=False),
        ),
    ]
