# Generated by Django 2.0.3 on 2018-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('grahpictype', models.CharField(choices=[('1', '建筑'), ('2', '道路'), ('3', '河流')], max_length=4)),
                ('context', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('mapid', models.Field(max_length=8, primary_key=True, serialize=False)),
                ('Maptype', models.CharField(choices=[('1', '多光谱'), ('2', '全色彩'), ('3', '混合')], max_length=8)),
                ('name', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('width', models.BigIntegerField()),
                ('height', models.BigIntegerField()),
                ('filepath', models.FileField(upload_to='')),
                ('cut_row', models.IntegerField()),
                ('cut_col', models.IntegerField()),
                ('gen_date', models.DateTimeField()),
                ('folder', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='SliceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slicemapid', models.CharField(max_length=8)),
                ('index_raw', models.IntegerField()),
                ('index_col', models.IntegerField()),
                ('filepath', models.FileField(upload_to='')),
            ],
        ),
    ]
