# Generated by Django 2.0.4 on 2018-04-24 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180418_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiclabel',
            name='coordinate_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='graphiclabel',
            name='coordinate_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='graphiclabel',
            name='graphic_provide',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='graphiclabel',
            name='square',
            field=models.FloatField(default=0),
        ),
    ]
